# Hides the generation timestamp when files are generated.
hideGenerationTimestamp: true
packageName: kuvera
packageVersion: 0.0.1
projectName: kuvera-api
# when accessing unset attribute, return `None` instead of raising `ApiAttributeError` (Default: false)
pythonAttrNoneIfUnset: true
gitRepoId: kuvera-py
gitUserId: captn3m0
httpUserAgent: Kuvera-Py/{packageVersion}